spring:
  application:
    name: zdzhai-order
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api
    username: root
    password: zzd
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
logging:
  config: classpath:logback-spring.xml
  level:
    com.zdzhai.order.mapper: trace
    #com:
      #zdzhai: debug
  #pattern:
    #console: '%d{yyyy-MM-dd hh:mm:ss} [%thread] %-5level %logger{50} - %msg%n'
    #console: '%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} === - %msg%n'
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
dubbo:
  application:
    name: zdzhai-order
  protocol:
    name: order
    port: -1
  registry:
    id: nacos-registry
    address: nacos://127.0.0.1:8848
rocketmq:
  name:
    server:
      addr: 127.0.0.1:9876
server:
  port: 7788
  servlet:
    context-path: /api